# Informações sobre a Global Tool dotnet-xunit-to-junit
# https://github.com/gabrielweyer/xunit-to-junit

name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PATH_PROJECT: ./Temperatura/Temperatura.csproj
  PATH_TESTS_PROJECT: ./Temperatura.Specs/Temperatura.Specs.csproj
  NUGET_SERVER: https://api.nuget.org/v3/index.json
  TEST_RESULTS_DIRECTORY: ./TestResults
  TEST_RESULTS_FILE: ./TestResults/resultado-testes.xml

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.201
    - name: Execução dos testes
      run: dotnet test ${{ env.PATH_TESTS_PROJECT }} --results-directory ${{ env.TEST_RESULTS_DIRECTORY }} --logger:"trx;LogFileName=resultado-testes.trx"
    - name: Exibir resultado da execução dos testes com xUnit
      if: always()
      run: |
        ls
        echo "Conteúdo do diretório ${{ env.TEST_RESULTS_DIRECTORY }}"
        cd ${{ env.TEST_RESULTS_DIRECTORY }}
        ls
        cat resultado-testes.trx
    - name: Instalar dotnet-xunit-to-junit
      if: always()
      run: dotnet tool install --global dotnet-xunit-to-junit --version 4.0.0
    - name: Criar Test Summary
      uses: test-summary/action@dist
      with:
        paths: ${{ env.TEST_RESULTS_FILE }}
      if: always()
      
  pack-push:
    needs: [tests]
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.201
    - name: Geração do package
      run: dotnet pack ${{ env.PATH_PROJECT }} -c Release -o out
    - name: Push no NuGet
      run: |
        cd out
        dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ env.NUGET_SERVER }} --skip-duplicate
